# Generated by Django 4.2.13 on 2024-05-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_num', models.FloatField()),
                ('second_num', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
